logging:
  level:
    edu.stanford.slac.eedformgatewayjava: DEBUG
    org.springdoc: debug

edu:
  stanford:
    slac:
      eed_java_backend_example:

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

spring:
  application:
    name: 'eed-java-backend-example'

# swagger-ui custom path
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs